{
    'name': 'Web ASVETEC',
    'version': '16.0.1.3.39',
    'summary': 'Sitio web de ASVETEC — RyS ASVETEC ltda., soluciones industriales norte de Chile',
    'description': 'Módulo que implementa el sitio web ASVETEC con snippets reutilizables: hero, categorías, productos, nosotros, marcas, servicios y contacto.',
    'category': 'Website',
    'license': 'LGPL-3',
    'author': 'Method',
    'depends': [
        'website',
        'website_sale',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/categories_data.xml',
        'data/website_data.xml',
        'data/brands_data.xml',
        'data/brands_default_flags.xml',
        'views/layout/asv_header.xml',
        'views/layout/asv_footer.xml',
        'views/layout/asv_shop_overrides.xml',
        'views/asvetec_brand_views.xml',
        'views/product_template_ribbon.xml',
        'views/snippets/s_asv_hero.xml',
        'views/snippets/s_asv_trust_bar.xml',
        'views/snippets/s_asv_categories.xml',
        'views/snippets/s_asv_featured_products.xml',
        'views/snippets/s_asv_about.xml',
        'views/snippets/s_asv_brands.xml',
        'views/snippets/s_asv_services.xml',
        'views/snippets/s_asv_contact.xml',
        'views/snippets/snippets.xml',
        'views/website_hero_image_view.xml',
        'views/pages/home.xml',
        'views/pages/cotizar_ok.xml',
        'views/pages/asv_contactus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'web_asvetec/static/src/scss/asv_backend.scss',
        ],
        'web.assets_frontend': [
            # Tokens CSS — debe ir primero
            'web_asvetec/static/src/scss/asv_tokens.scss',
            # Layout base
            'web_asvetec/static/src/scss/asv_layout.scss',
            'web_asvetec/static/src/scss/asv_footer.scss',
            'web_asvetec/static/src/scss/asv_shop.scss',
            # Snippets
            'web_asvetec/static/src/scss/snippets/s_asv_hero.scss',
            'web_asvetec/static/src/scss/snippets/s_asv_trust_bar.scss',
            'web_asvetec/static/src/scss/snippets/s_asv_categories.scss',
            'web_asvetec/static/src/scss/snippets/s_asv_featured_products.scss',
            'web_asvetec/static/src/scss/snippets/s_asv_about.scss',
            'web_asvetec/static/src/scss/snippets/s_asv_brands.scss',
            'web_asvetec/static/src/scss/snippets/s_asv_services.scss',
            'web_asvetec/static/src/scss/snippets/s_asv_contact.scss',
            # JavaScript
            'web_asvetec/static/src/js/snippets/s_asv_hero/000.js',
            'web_asvetec/static/src/js/snippets/s_asv_brands/000.js',
            'web_asvetec/static/src/js/snippets/s_asv_featured_products/000.js',
            'web_asvetec/static/src/js/snippets/s_asv_categories/000.js',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
}
